#!/usr/bin/env python3

# Author: Milan Nikolic <gen2brain@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import os
import sys
import atexit
import shutil
import signal
import tempfile

from PyQt5.QtWidgets import QApplication

curdir = os.path.dirname(os.path.abspath(__file__))
os.chdir(curdir)

if os.path.isdir(os.path.join(curdir, "src", "bukanir")) \
        and os.path.isfile(os.path.join(curdir, "setup.py")):
    sys.path.insert(0, os.path.realpath(os.path.join(curdir, "src")))

from bukanir import APP_NAME
from bukanir.main import MainWindow


def rm_tmp(tmpdir):
    try:
        shutil.rmtree(tmpdir)
    except:
        pass


if __name__ == "__main__":
    signal.signal(signal.SIGINT, signal.SIG_DFL)

    app = QApplication(sys.argv)
    from bukanir.opts import opts, args

    app.setApplicationName(APP_NAME.title())

    tmpdir = tempfile.mkdtemp(APP_NAME)
    atexit.register(rm_tmp, tmpdir)

    window = MainWindow(tmpdir, (opts, args))
    window.show()
    window.raise_()
    sys.exit(app.exec_())
