// Java Package main is a proxy for talking to a Go program.
//   gobind -lang=java bukanir
//
// File is generated by gobind. Do not edit.
package go.main;

import go.Seq;

public abstract class Main {
    private Main() {} // uninstantiable
    
    public static String AutoComplete(String query, long limit) throws Exception {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        String _result;
        _in.writeUTF16(query);
        _in.writeInt(limit);
        Seq.send(DESCRIPTOR, CALL_AutoComplete, _in, _out);
        _result = _out.readUTF16();
        String _err = _out.readUTF16();
        if (_err != null) {
            throw new Exception(_err);
        }
        return _result;
    }
    
    public static String Category(String category, long limit, long force, String tmpDir) throws Exception {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        String _result;
        _in.writeUTF16(category);
        _in.writeInt(limit);
        _in.writeInt(force);
        _in.writeUTF16(tmpDir);
        Seq.send(DESCRIPTOR, CALL_Category, _in, _out);
        _result = _out.readUTF16();
        String _err = _out.readUTF16();
        if (_err != null) {
            throw new Exception(_err);
        }
        return _result;
    }
    
    public static String Search(String query, long limit) throws Exception {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        String _result;
        _in.writeUTF16(query);
        _in.writeInt(limit);
        Seq.send(DESCRIPTOR, CALL_Search, _in, _out);
        _result = _out.readUTF16();
        String _err = _out.readUTF16();
        if (_err != null) {
            throw new Exception(_err);
        }
        return _result;
    }
    
    public static String Subtitle(String movie, String year, String release, String language, long category, long season, long episode, String imdbID) throws Exception {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        String _result;
        _in.writeUTF16(movie);
        _in.writeUTF16(year);
        _in.writeUTF16(release);
        _in.writeUTF16(language);
        _in.writeInt(category);
        _in.writeInt(season);
        _in.writeInt(episode);
        _in.writeUTF16(imdbID);
        Seq.send(DESCRIPTOR, CALL_Subtitle, _in, _out);
        _result = _out.readUTF16();
        String _err = _out.readUTF16();
        if (_err != null) {
            throw new Exception(_err);
        }
        return _result;
    }
    
    public static String Summary(long id, long category, long season) throws Exception {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        String _result;
        _in.writeInt(id);
        _in.writeInt(category);
        _in.writeInt(season);
        Seq.send(DESCRIPTOR, CALL_Summary, _in, _out);
        _result = _out.readUTF16();
        String _err = _out.readUTF16();
        if (_err != null) {
            throw new Exception(_err);
        }
        return _result;
    }
    
    private static final int CALL_AutoComplete = 1;
    private static final int CALL_Category = 2;
    private static final int CALL_Search = 3;
    private static final int CALL_Subtitle = 4;
    private static final int CALL_Summary = 5;
    private static final String DESCRIPTOR = "main";
}
